In [1]:
import numpy as np
print("This program demonstrates use of numpy-matrix.")
row = int(input("Enter amount of rows:\n"))
col = int(input("Enter number of columns:\n"))

print("Zero-matrix of the given rows & columns is:")
z_array = np.zeros((col, row), dtype=int)
print(z_array)

array = np.arange(col * row).reshape(row, col)

print("Matrix printed with np-formatting:")

n_sorted = []
row_index = 0
for rows in z_array:
    column_index = 0
    for item in rows:
        item = (row_index + 1)*(column_index + 1)
        z_array[row_index][column_index] = item
        column_index = column_index + 1
        n_sorted.append(item)
    row_index = row_index + 1
print(z_array, '\n')
print("Matrix sorted into one array:")
print(np.sort(z_array, axis=None))
print("Matrix printed with elements separated by semicolons:")
for rows in z_array:
    print("{};{};{};{};".format(rows[0], rows[1], rows[2], rows[3]))
print("")
    
while True:
    try:
        print("Shaping the matrix. Please, enter the new dimensions.")
        nrow = int(input("Enter amount of new rows:\n"))
        ncol = int(input("Enter number of new columns:\n"))
        reshape = z_array.reshape(nrow,ncol)
    except:
        print("Faulty shape. Please, try again.")
        continue
    else:
        break

print("Newly shaped matrix is:")
print(reshape)

line = np.sort(z_array, axis=None)
print("Largest number in the matrix is:", max(line))
print("Smallest number in the matrix is:", min(line))
print("Sum of all values in the matrix is:", sum(line))
list_values=[int(item) for item in input("Enter the list items : ").split()]
np_list = np.array(list_values)
print("Unique values are:", np.unique(np_list))
print(" ")
result = ' '.join(str(item) for item in sorted(set(list_values)))
print("Unique values are: [{}]".format(result))

This program demonstrates use of numpy-matrix.
Enter amount of rows:
4
Enter number of columns:
4
Zero-matrix of the given rows & columns is:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Matrix printed with np-formatting:
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]] 

Matrix sorted into one array:
[ 1  2  2  3  3  4  4  4  6  6  8  8  9 12 12 16]
Matrix printed with elements separated by semicolons:
1;2;3;4;
2;4;6;8;
3;6;9;12;
4;8;12;16;

Shaping the matrix. Please, enter the new dimensions.
Enter amount of new rows:
8
Enter number of new columns:
2
Newly shaped matrix is:
[[ 1  2]
 [ 3  4]
 [ 2  4]
 [ 6  8]
 [ 3  6]
 [ 9 12]
 [ 4  8]
 [12 16]]
Largest number in the matrix is: 16
Smallest number in the matrix is: 1
Sum of all values in the matrix is: 100
Enter the list items : 11 11 12 13 13 15 16 16 18 18 22 22 18 5 5 44 3 4 55 32 34 44 3
Unique values are: [ 3  4  5 11 12 13 15 16 18 22 32 34 44 55]
 
Unique values are: [3 4 5 11 12 13 15 16 18 22 32 34 44 55]


4#### 